# Generated by Django 4.2.20 on 2025-03-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
