# Generated by Django 4.2.20 on 2025-04-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='personalisation_details',
        ),
    ]
