# Generated by Django 4.2.20 on 2025-04-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
